name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  IMAGE_NAME: http_request_logger

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push-linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Dockerfile.linux --tag $IMAGE_NAME

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  push-windows:
    runs-on: windows-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Dockerfile.windowsservercore --tag ${Env:IMAGE_NAME}

      - name: Push image
        run: |
          $IMAGE_ID="docker.pkg.github.com/${Env:github.repository}/${Env:IMAGE_NAME}"
          $VERSION="latest-windowsservercore"

          Write-Host "IMAGE_ID=${IMAGE_ID}"
          Write-Host "VERSION=${VERSION}"

          docker tag ${Env:IMAGE_NAME} ${IMAGE_ID}:${VERSION}
          docker push ${IMAGE_ID}:${VERSION}
